### ISSUE TITLE
dear processor, where can i get the source  code of the LOE

### ISSUE THREAD

**Issue by GY5134** [steffensbola/bling_iqa_contrast#2]
dear professor, where can I get the source code of the LOE. When I clicked on the link URL of LOE, I found that this is not the reference you provided, so I took the liberty to leave a message for you and ask you the location of the source code.

**Comment by steffensbola** [comment]
Hi,
We have provided one implementation in this exact repo on **/LOE/LOE.m**.

This code is pretty much a replica from **https://github.com/baidut/BIMEF/blob/master/quality/loe100x100.m** (which is inside the repo we linked to) adapted to work with Octave.
